using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Backend.Data;
using Backend.Domain.Entities;
using Backend.Domain.Interfaces;
using Backend.Infrastructure.Correlation;

namespace Backend.Services;

/// <summary>
/// Service for correlation operations
/// </summary>
public class CorrelationService : ICorrelationService
{
    private readonly SimpleRuleEngine _ruleEngine;
    private readonly ApplicationDbContext _context;
    private readonly ILogRepository _logRepository;
    private readonly ILogger<CorrelationService> _logger;

    public CorrelationService(
        SimpleRuleEngine ruleEngine,
        ApplicationDbContext context,
        ILogRepository logRepository,
        ILogger<CorrelationService> logger)
    {
        _ruleEngine = ruleEngine;
        _context = context;
        _logRepository = logRepository;
        _logger = logger;
    }

    public async Task<object> GetStatisticsAsync(DateTime? startDate = null, DateTime? endDate = null, CancellationToken cancellationToken = default)
    {
        var start = startDate ?? DateTime.UtcNow.AddDays(-7);
        var end = endDate ?? DateTime.UtcNow;

        // Get alerts generated by correlation engine
        var correlationAlerts = await _context.Alerts
            .Where(a => a.Source == "CorrelationEngine" &&
                       a.CreatedAt >= start && a.CreatedAt <= end)
            .ToListAsync(cancellationToken);

        var ruleBreakdown = correlationAlerts
            .GroupBy(a => a.Title)
            .Select(g => new { RuleName = g.Key, Count = g.Count() })
            .ToList();

        var severityBreakdown = correlationAlerts
            .GroupBy(a => a.Severity)
            .Select(g => new { Severity = g.Key.ToString(), Count = g.Count() })
            .ToList();

        return new
        {
            TotalCorrelationAlerts = correlationAlerts.Count,
            RuleBreakdown = ruleBreakdown,
            SeverityBreakdown = severityBreakdown,
            TimeRange = new { Start = start, End = end }
        };
    }

    public Task<IEnumerable<object>> GetRulesAsync(CancellationToken cancellationToken = default)
    {
        // Return predefined rules (in production, these would come from database)
        return Task.FromResult<IEnumerable<object>>(new[]
        {
            new { Name = "Brute Force Attack", Description = "5+ failed logins from same IP", Threshold = 5, TimeWindow = 5 },
            new { Name = "Credential Stuffing", Description = "10+ failed logins for different users", Threshold = 10, TimeWindow = 10 },
            new { Name = "Privilege Escalation", Description = "Successful login after failures", Threshold = 1, TimeWindow = 15 },
            new { Name = "Port Scanning", Description = "20+ connection attempts to different ports", Threshold = 20, TimeWindow = 5 },
            new { Name = "Suspicious Process Execution", Description = "10+ process creations in short time", Threshold = 10, TimeWindow = 2 }
        });
    }

    public async Task<CorrelationResult?> TriggerCorrelationAsync(string logEntryId, CancellationToken cancellationToken = default)
    {
        var logEntry = await _logRepository.GetByIdAsync(logEntryId, cancellationToken);
        if (logEntry == null)
        {
            _logger.LogWarning("Log entry not found: {LogEntryId}", logEntryId);
            return null;
        }

        if (logEntry.NormalizedFields == null)
        {
            _logger.LogWarning("Log entry is not normalized: {LogEntryId}", logEntryId);
            return null;
        }

        // Get related logs function
        async Task<List<LogEntry>> GetRelatedLogsAsync(
            string correlationKey,
            DateTime startTime,
            DateTime endTime)
        {
            var parts = correlationKey.Split(':');
            if (parts.Length != 2)
                return new List<LogEntry>();

            var keyType = parts[0];
            var keyValue = parts[1];

            var logs = await _logRepository.GetNormalizedLogsByFieldAsync(
                keyType == "ip" ? "SourceIp" : "UserName",
                keyValue,
                startTime,
                endTime,
                cancellationToken);

            return logs.ToList();
        }

        var results = await _ruleEngine.ProcessLogAsync(
            logEntry,
            GetRelatedLogsAsync,
            cancellationToken);

        return results.FirstOrDefault();
    }
}
