# AthalaSIEM Configuration File

# Server Configuration
server:
  host: "localhost"
  port: 8080
  debug: false

# Database Configuration
database:
  host: "localhost"
  port: 5432
  name: "athala_siem"
  user: "admin"
  password: "your_password_here"

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/athala_siem.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# Security Configuration
security:
  secret_key: "fae1044cf8b3c10cbe8c50933f090633593372e61db672db0873e27cc96438c3" #1[}4j$P!u#1Z:Z2v
  token_expiration: 3600  # seconds

# Features Configuration
features:
  enable_alerts: true
  enable_reporting: true
  enable_dashboard: true