evaluation:
  metrics:
  - accuracy
  - precision
  - recall
  - f1
  threshold: 0.5
model_settings:
  anomaly_detector:
    input_dim: 512
    hidden_dim: 256
  vae:
    input_dim: 512
    hidden_dims: [256, 128]
    latent_dim: 64
  threat_detector:
    input_dim: 512
    hidden_dim: 256
    num_classes: 2
  batch_size: 32
  early_stopping_patience: 5
  epochs: 10
  learning_rate: 0.001
  validation_split: 0.2
optimization:
  enable_mixed_precision: true
  gradient_clipping: true
  max_gradient_norm: 1.0
paths:
  checkpoint_dir: checkpoints/
  log_dir: logs/
  model_dir: models/
training:
  checkpoint_frequency: 5
  enable_checkpoints: true
  enable_early_stopping: true
  max_epochs_without_improvement: 10

feature_toggles:
  anomaly_detection: true
  threat_detection: true
  adaptive_learning: true
