using Microsoft.AspNetCore.SignalR;

namespace Backend.Hubs;

/// <summary>
/// SignalR Hub for real-time SIEM event streaming to the frontend dashboard.
/// Clients can subscribe to specific channels:
///   - "ReceiveLog"       : new log entries as they arrive from agents
///   - "ReceiveAlert"     : new alerts generated by the detection engine
///   - "AgentStatusChange": agent online/offline transitions
/// </summary>
public class SiemHub : Hub
{
    private readonly ILogger<SiemHub> _logger;

    public SiemHub(ILogger<SiemHub> logger)
    {
        _logger = logger;
    }

    public override Task OnConnectedAsync()
    {
        _logger.LogInformation("Dashboard client connected: {ConnectionId}", Context.ConnectionId);
        return base.OnConnectedAsync();
    }

    public override Task OnDisconnectedAsync(Exception? exception)
    {
        _logger.LogInformation("Dashboard client disconnected: {ConnectionId}", Context.ConnectionId);
        return base.OnDisconnectedAsync(exception);
    }

    /// <summary>
    /// Allows clients to subscribe to logs from a specific agent.
    /// </summary>
    public async Task SubscribeToAgent(string agentId)
    {
        await Groups.AddToGroupAsync(Context.ConnectionId, $"agent-{agentId}");
        _logger.LogDebug("Client {ConnectionId} subscribed to agent {AgentId}", Context.ConnectionId, agentId);
    }

    /// <summary>
    /// Allows clients to unsubscribe from a specific agent.
    /// </summary>
    public async Task UnsubscribeFromAgent(string agentId)
    {
        await Groups.RemoveFromGroupAsync(Context.ConnectionId, $"agent-{agentId}");
    }
}
