'use client'

import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Button } from '@/components/ui/button'
import { useCorrelationStatistics, useCorrelationRules, useTriggerCorrelation } from '@/hooks/useCorrelation'
import { CorrelationStats } from '@/components/Correlation/CorrelationStats'
import { CorrelationRulesList } from '@/components/Correlation/CorrelationRulesList'
import { CorrelationAlerts } from '@/components/Correlation/CorrelationAlerts'
import { RulePerformanceChart } from '@/components/Correlation/RulePerformanceChart'
import { TriggerCorrelationDialog } from '@/components/Correlation/TriggerCorrelationDialog'
import { Shield, List, AlertTriangle, BarChart3, Play } from 'lucide-react'

export default function CorrelationPage() {
  const [dateRange, setDateRange] = useState<{ start?: string; end?: string }>({
    start: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    end: new Date().toISOString(),
  })
  const [showTriggerDialog, setShowTriggerDialog] = useState(false)

  const { data: statistics, isLoading: statsLoading } = useCorrelationStatistics(
    dateRange.start,
    dateRange.end
  )
  const { data: rules, isLoading: rulesLoading } = useCorrelationRules()
  const triggerCorrelation = useTriggerCorrelation()

  return (
    <div className="p-6 space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Correlation Engine</h1>
          <p className="text-muted-foreground">
            View correlation rules, statistics, and triggered alerts
          </p>
        </div>
        <Button onClick={() => setShowTriggerDialog(true)}>
          <Play className="w-4 h-4 mr-2" />
          Trigger Correlation
        </Button>
      </div>

      <Tabs defaultValue="overview" className="space-y-6">
        <TabsList>
          <TabsTrigger value="overview">
            <BarChart3 className="w-4 h-4 mr-2" />
            Overview
          </TabsTrigger>
          <TabsTrigger value="rules">
            <List className="w-4 h-4 mr-2" />
            Active Rules
          </TabsTrigger>
          <TabsTrigger value="alerts">
            <AlertTriangle className="w-4 h-4 mr-2" />
            Correlation Alerts
          </TabsTrigger>
        </TabsList>

        <TabsContent value="overview" className="space-y-6">
          {/* Statistics Cards */}
          <CorrelationStats statistics={statistics} isLoading={statsLoading} />

          {/* Rule Performance Chart */}
          <Card>
            <CardHeader>
              <CardTitle>Rule Performance</CardTitle>
              <CardDescription>Correlation rule trigger frequency</CardDescription>
            </CardHeader>
            <CardContent>
              <RulePerformanceChart data={statistics?.ruleBreakdown || []} />
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="rules" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Active Correlation Rules</CardTitle>
              <CardDescription>
                Predefined rules that detect security patterns (e.g., 5 failed logins = Brute Force)
              </CardDescription>
            </CardHeader>
            <CardContent>
              <CorrelationRulesList rules={rules || []} isLoading={rulesLoading} />
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="alerts" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Correlation Alerts</CardTitle>
              <CardDescription>
                Alerts generated by correlation rules
              </CardDescription>
            </CardHeader>
            <CardContent>
              <CorrelationAlerts dateRange={dateRange} />
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      <TriggerCorrelationDialog
        open={showTriggerDialog}
        onOpenChange={setShowTriggerDialog}
        onTrigger={triggerCorrelation.mutate}
        isLoading={triggerCorrelation.isPending}
      />
    </div>
  )
}
