# AI System Settings
ai_enabled: true

model:
  name: donquixote
  version: 1.0.0
  type: transformer
  embedding_dim: 768
  num_heads: 12
  num_layers: 6
  dropout: 0.1
  input_dim: 128
  hidden_size: 256
  num_layers: 2

  anomaly_detector:
    latent_dim: 32
    hidden_layers: [64, 32]
    learning_rate: 0.001
    
  threat_detector:
    hidden_dim: 128
    num_layers: 2
    dropout: 0.1
    learning_rate: 0.001

model_settings:
  use_lightweight_model: true
  enable_gpu: true  # Aktifkan GPU jika tersedia
  model_precision: "float32"
  architecture: "transformer"
  embedding_dim: 768
  num_heads: 12
  num_layers: 6
  dropout: 0.1
  max_sequence_length: 512
  vocab_size: 30000
  use_gpu: true
  batch_size: 32

training:
  batch_size: 32
  num_epochs: 100
  validation_split: 0.2
  early_stopping_patience: 10
  
inference:
  threshold_confidence: 0.85
  max_batch_size: 16
  timeout_seconds: 30
  enable_gpu: true

features:
  threat_detection: true
  anomaly_detection: true
  behavior_analysis: true
  pattern_recognition: true

# Resource Limits
resource_settings:
  max_memory_usage: 2048  # MB
  max_cpu_usage: 50      # Percentage
  batch_size: 32
  num_workers: 2

# Model Settings
model_settings:
  use_lightweight_model: true
  enable_gpu: false
  model_precision: "float32"

# Feature Toggles
feature_toggles:
  anomaly_detection: true
  threat_detection: true
  adaptive_learning: false

paths:
  checkpoints: checkpoints
  logs: logs

monitoring:
  max_memory_usage: 0.8
  max_gpu_memory: 0.9

paths:
  model_save_dir: "models/"
  log_dir: "logs/"