export const API_ENDPOINTS = {
    AUTH: {
      LOGIN: '/auth/login',
      LOGOUT: '/auth/logout',
      REGISTER: '/auth/register',
      ME: '/auth/me',
      REFRESH_TOKEN: '/auth/refresh-token',
      CHANGE_PASSWORD: '/auth/change-password',
    },
    ALERTS: {
      LIST: '/alerts',
      DETAIL: (id: string) => `/alerts/${id}`,
      CREATE: '/alerts',
      UPDATE: (id: string) => `/alerts/${id}`,
      DELETE: (id: string) => `/alerts/${id}`,
      BULK_UPDATE: '/alerts/bulk-update',
      STATISTICS: '/alerts/statistics',
      SEVERITY_DISTRIBUTION: '/alerts/severity-distribution',
      TIME_DISTRIBUTION: '/alerts/time-distribution',
      EXPORT: '/alerts/export',
    },
    LOGS: {
      LIST: '/logs',
      DETAIL: (id: string) => `/logs/${id}`,
      SEARCH: '/logs/search',
      AGGREGATE: '/logs/aggregate',
      EXPORT: '/logs/export',
      SOURCES: '/logs/sources',
      TYPES: '/logs/types',
      STATISTICS: '/logs/statistics',
    },
    METRICS: {
      SUMMARY: '/metrics/summary',
      TRENDS: '/metrics/trends',
      SECURITY_SCORE: '/metrics/security-score',
      SYSTEM_HEALTH: '/metrics/system-health',
      PERFORMANCE: '/metrics/performance',
      RESOURCE_USAGE: '/metrics/resource-usage',
    },
    REPORTS: {
      LIST: '/reports',
      GENERATE: '/reports/generate',
      DOWNLOAD: (id: string) => `/reports/${id}/download`,
      TEMPLATES: '/reports/templates',
      SCHEDULE: '/reports/schedule',
    },
    USERS: {
      LIST: '/users',
      DETAIL: (id: string) => `/users/${id}`,
      CREATE: '/users',
      UPDATE: (id: string) => `/users/${id}`,
      DELETE: (id: string) => `/users/${id}`,
      ROLES: '/users/roles',
      PERMISSIONS: '/users/permissions',
    },
    SETTINGS: {
      GENERAL: '/settings/general',
      NOTIFICATIONS: '/settings/notifications',
      INTEGRATION: '/settings/integration',
      BACKUP: '/settings/backup',
      RETENTION: '/settings/retention',
    },
    DASHBOARD: {
      OVERVIEW: '/dashboard/overview',
      WIDGETS: '/dashboard/widgets',
      CUSTOMIZE: '/dashboard/customize',
    }
  }